### ISSUE TITLE
Create login screen 

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/dashboard#1]
This is quite easy and self-explanatory.
Beaker Server is able to authenticate the upcoming users. Therefore we can implement the following part
- New Login screen
- BasicAuth mechanism, Beaker returns cookies on successful auth.
- Showing identity on the main bar.
- Login Service

https://beaker-project.github.io/beaker-next-design/designs/login/

**Comment by renanrodrigo** [comment]
Currently, the `/login` endpoint is accepting `x-www-form-urlencoded` data, and is always redirecting you to some provided path.
I see that thanks to myself ( https://github.com/beaker-project/beaker/commit/90066ad68d9de407c5c05e08b984608b6928af8d ) Beaker ignores any path in any different URL.
- Are we changing this to be restful?
- Are we always running the new UI always in the same server as the API? If affirmative, we need to disable the `/` cherry endpoint, so I can redirect myself to my own UI :|

**Comment by StykMartin** [comment]
I mean you should use `"/auth/login" (POST)`
You will send auth header and it will return a cookie to you.

**Comment by renanrodrigo** [comment]
HHHHMMMMMMMMMMMMMM me looking at the API like Mr. Magoo
